eci_node:
  ros__parameters:
    input_topic: /sim/point_cloud
    output_topic: /eci_value

    voxel_size: 0.01
    max_points: 3000.0
    max_distance: 5.0

    min_height: 0.05
    max_height: 1.0

    density_distance: 3.0
    density_half_fov_deg: 45.0
    width_half_fov_deg: 30.0

    no_cloud_reset_sec: 8.0
    eci_publish_hz: 20.0

    enable_range_visualization: true
    range_marker_topic: /eci_detection_range
    range_target_frame: /Leatherback
